server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
#          // local path
#          uri: file://C:/MyProject/work/git-local-repo
#          // remote path
          uri: https://github.com/honeydanji/spring-cloud-config-test
          username: tjdwls3680@naver.com
          password: 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